# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_body'),
        ('festivaluser', '0002_auto_20160411_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivaladvisoruser',
            name='favorite_festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.FestivalPage'),
        ),
    ]
