# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivaluser', '0003_festivaladvisoruser_favorite_festival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivaladvisoruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='festprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
