# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_content_type', to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
