# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentwithtitle',
            name='comment',
            field=models.TextField(max_length=700, verbose_name='comment'),
        ),
    ]
