# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160411_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentwithtitle',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='commentwithtitle',
            unique_together=set([('content_type', 'object_pk', 'user')]),
        ),
    ]
