# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('votes', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 4, 14, 8, 19, 130174), editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
