# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20160304_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 4, 14, 12, 15, 448803, tzinfo=utc), editable=False),
        ),
    ]
