# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20160304_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='date_added',
        ),
        migrations.AddField(
            model_name='vote',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 4, 14, 44, 39, 382047, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
