# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20160416_1738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([]),
        ),
    ]
