# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 19:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20160531_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
