# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20160317_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_score', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_vote', to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
