# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20160601_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
