# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_auto_20160602_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
