# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressorderable',
            name='address_ptr',
        ),
        migrations.RemoveField(
            model_name='addressorderable',
            name='page',
        ),
        migrations.RemoveField(
            model_name='orderabletest',
            name='location_ptr',
        ),
        migrations.RemoveField(
            model_name='orderabletest',
            name='page',
        ),
        migrations.DeleteModel(
            name='AddressOrderable',
        ),
        migrations.DeleteModel(
            name='OrderableTest',
        ),
    ]
