# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_squashed_0024_festivalpageperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=28, unique=True, verbose_name='naam'),
        ),
    ]
