# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160406_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalpage',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festivals', to='home.Person'),
        ),
    ]
