# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160413_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdresOrderable',
            new_name='AddressOrderable',
        ),
    ]
