# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Startpagina'},
        ),
    ]
