# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 16:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160415_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tja', to='home.FestivalPage'),
        ),
    ]
