# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160415_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalpageperson',
            name='page',
        ),
        migrations.RemoveField(
            model_name='festivalpageperson',
            name='person_ptr',
        ),
        migrations.DeleteModel(
            name='FestivalPagePerson',
        ),
    ]
