# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 09:50
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
