# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160411_1006'),
        ('home', '0005_auto_20160415_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSnippet',
            fields=[
                ('commentwithtitle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comments.CommentWithTitle')),
            ],
            options={
                'verbose_name_plural': 'comments',
                'ordering': ('submit_date',),
                'permissions': [('can_moderate', 'Can moderate comments')],
                'verbose_name': 'comment',
                'abstract': False,
            },
            bases=('comments.commentwithtitle',),
        ),
    ]
