# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160411_1006'),
        ('home', '0005_homepage_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentWithTitleSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.CommentWithTitle')),
            ],
        ),
    ]
