# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160411_1006'),
        ('home', '0006_commentwithtitlesnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSnippet',
            fields=[
                ('commentwithtitle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comments.CommentWithTitle')),
            ],
            options={
                'verbose_name_plural': 'comments',
                'permissions': [('can_moderate', 'Can moderate comments')],
                'abstract': False,
                'verbose_name': 'comment',
                'ordering': ('submit_date',),
            },
            bases=('comments.commentwithtitle',),
        ),
    ]
