# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160411_1006'),
        ('home', '0007_testsnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSnippet',
            fields=[
                ('commentwithtitle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comments.CommentWithTitle')),
            ],
            options={
                'permissions': [('can_moderate', 'Can moderate comments')],
                'abstract': False,
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('submit_date',),
            },
            bases=('comments.commentwithtitle',),
        ),
        migrations.RemoveField(
            model_name='commentwithtitlesnippet',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='testsnippet',
            name='commentwithtitle_ptr',
        ),
        migrations.DeleteModel(
            name='CommentWithTitleSnippet',
        ),
        migrations.DeleteModel(
            name='TestSnippet',
        ),
    ]
