# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_festivalpagerelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalpagerateableattribute',
            name='name',
            field=models.CharField(max_length=27, unique=True),
        ),
    ]
