# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 17:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpage',
            name='pricing',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Prijs (range 0 - 5)'),
        ),
    ]
