# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160412_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderableTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=8)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaties', to='home.FestivalPage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='customimage',
            name='author',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='auteur'),
        ),
    ]
