# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_addressinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpagerateableattribute',
            name='attribute',
            field=models.CharField(default='', max_length=12),
        ),
    ]
