# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_festivalpagerateableattribute_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpagerateableattribute',
            name='rateable_attribute',
            field=models.CharField(default='', max_length=16),
        ),
    ]
