# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20160413_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderabletest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Location'),
        ),
    ]
