# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_orderabletest_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderabletest',
            name='page',
        ),
        migrations.RemoveField(
            model_name='orderabletest',
            name='test',
        ),
        migrations.DeleteModel(
            name='OrderableTest',
        ),
    ]
