# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_festivalpagerateableattribute_rateable_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festivalpageratebleattributevalue',
            old_name='attribute',
            new_name='rateable_attribute',
        ),
    ]
