# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160319_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalpageratebleattributevalue',
            name='rateable_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tja', to='home.FestivalPageRateableAttribute'),
        ),
    ]
