# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160427_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpage',
            name='general_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='festivalpage',
            name='num_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
