# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20160430_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpageratebleattributevalue',
            name='applicable',
            field=models.BooleanField(default=True, verbose_name='van toepassing?'),
        ),
    ]
