# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20160319_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalpage',
            name='rateable_attribute',
        ),
    ]
