# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import modelcluster.contrib.taggit
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_festivalpageratebleattributevalue_applicable'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='festivalpage',
            managers=[
                ('featured', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default='', help_text='Hier kan je een promo tekstje invullen, al dan niet voorzien van extra tekst styling', verbose_name='Festival promo tekst'),
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='duration',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(21)], verbose_name='Duur (# dagen)'),
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='name',
            field=models.CharField(default='', help_text='Dit moet een unieke naam zijn!', max_length=40, unique=True, verbose_name='Festival naam'),
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='pricing',
            field=models.PositiveIntegerField(default=0, help_text='0 = gratis, 1 = <20€, 2 = <50€, 3 = <100€, 4 = <200€ en 5= >200€', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Prijs (range 0 - 5)'),
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Wordt gebruikt om festivals te filteren, dus het <b><u>genre</u></b> (of genres) zijn ideaal om hier in te geven.', through='home.FestivalPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='website',
            field=models.URLField(blank=True, help_text='De link naar de homepage van het festival', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='festivalpageratebleattributevalue',
            name='rateable_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.FestivalPageRateableAttribute', verbose_name='eigenschap'),
        ),
    ]
