# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_location2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location2',
            name='address',
        ),
        migrations.DeleteModel(
            name='Location2',
        ),
    ]
