# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20160413_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=28, verbose_name='locatie naam')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location2', to='home.Address', verbose_name='adres')),
            ],
            options={
                'verbose_name': 'locatie2',
                'verbose_name_plural': 'locaties2',
            },
        ),
    ]
