# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20160503_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendition',
            name='image',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='home.CustomImage'),
        ),
    ]
