# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20160503_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalimage',
            name='image',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.CustomImage', verbose_name='afbeelding'),
        ),
    ]
