# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20160320_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpage',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=28, null=True),
        ),
    ]
