# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20160503_2033'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='festivalpage',
            managers=[
            ],
        ),
    ]
