# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20160506_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpage',
            name='test',
            field=models.BooleanField(default=True, verbose_name='test'),
        ),
    ]
