# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20160320_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpage',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festivals', to='home.Person'),
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
