# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_festivalpageperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalpageperson',
            name='page',
        ),
        migrations.DeleteModel(
            name='FestivalPagePerson',
        ),
    ]
