# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20160523_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalpage',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festivals', to='home.Location'),
        ),
    ]
