# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_blogindexpage_blogpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='url_title',
        ),
    ]
