# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20160322_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Location')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='home.FestivalPage')),
            ],
        ),
    ]
