# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20160402_2050'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='festivalpage',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='festivalpage',
            old_name='descr',
            new_name='description',
        ),
    ]
