# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 07:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20160622_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='blog_content',
            field=wagtail.wagtailcore.fields.StreamField((('blog_title', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('title', wagtail.wagtailcore.blocks.CharBlock()), ('auteur', wagtail.wagtailcore.blocks.CharBlock())), help_text='Dit is de titel van het artikel, voorzien van een afbeelding')), ('intro', wagtail.wagtailcore.blocks.StructBlock((('intro', wagtail.wagtailcore.blocks.CharBlock(label='Inleiding van het artikel', required=True)),), help_text='Hiermee kan je optioneel een korte inleiding voorzien')), ('subtitle', home.models.Heading2Block()), ('video', wagtail.wagtailcore.blocks.StructBlock((('link', wagtail.wagtailembeds.blocks.EmbedBlock(classname='block-background', label='URL van video', required=True)), ('titel', wagtail.wagtailcore.blocks.CharBlock(label='Titel', required=True)), ('desc', wagtail.wagtailcore.blocks.CharBlock(label='Beschrijving van video, optioneel', required=False))))), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock(help_text='Geef de afbeelding een korte beschrijving', max_length=180, required=True))))), ('quote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.CharBlock(help_text='Geef hier een citaat in', label='Citaat', max_length=150, required=True)), ('person', wagtail.wagtailcore.blocks.CharBlock(help_text='Van wie is dit citaat?', label='Auteur', max_length=28, required=True))))), ('vid', wagtail.wagtailembeds.blocks.EmbedBlock()))),
        ),
    ]
