# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_blogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(max_length=40, null=True, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='blog_content',
            field=wagtail.wagtailcore.fields.StreamField((('blog_title', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('title', wagtail.wagtailcore.blocks.CharBlock()), ('auteur', wagtail.wagtailcore.blocks.CharBlock())), help_text='Dit is de titel van het artikel, voorzien van een afbeelding')), ('blogintro', wagtail.wagtailcore.blocks.StructBlock((('intro', wagtail.wagtailcore.blocks.TextBlock(label='Inleiding van het artikel', required=True)),), help_text='Hiermee kan je optioneel een korte inleiding voorzien')), ('subtitle', home.models.Heading2Block()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock(help_text='Geef de afbeelding een korte beschrijving', max_length=180, required=True))))), ('quote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.CharBlock(help_text='Geef hier een citaat in', label='Citaat', max_length=150, required=True)), ('person', wagtail.wagtailcore.blocks.CharBlock(help_text='Van wie is dit citaat?', label='Auteur', max_length=28, required=True)))))), verbose_name='Blog inhoud'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date_posted',
            field=models.DateField(default=datetime.date.today, verbose_name='Publicatie datum'),
        ),
    ]
