# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20160624_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='url',
            field=models.CharField(default='', help_text='Is nodig om unieke URL voor blog artikel aan te maken', max_length=255, verbose_name='URL title'),
        ),
    ]
