# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_festivalpage_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalpage',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festivals', to='home.Person'),
        ),
    ]
