# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20160404_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=40, verbose_name='stad'),
        ),
        migrations.AlterField(
            model_name='festivalpageratebleattributevalue',
            name='rateable_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.FestivalPageRateableAttribute', unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email adres'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=28, verbose_name='voornaam'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='familienaam'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=28, null=True, verbose_name='telefoonnummer'),
        ),
        migrations.AlterUniqueTogether(
            name='festivalpageratebleattributevalue',
            unique_together=set([]),
        ),
    ]
