# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20160405_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='uploaded_by_user',
        ),
        migrations.AlterUniqueTogether(
            name='customrendition',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='customrendition',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='customrendition',
            name='image',
        ),
        migrations.DeleteModel(
            name='CustomImage',
        ),
        migrations.DeleteModel(
            name='CustomRendition',
        ),
    ]
