# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20160405_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festivalpage',
            options={'ordering': ['-date'], 'verbose_name': 'Festival'},
        ),
    ]
