# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalPageRateableAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=27)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FestivalPage')),
            ],
            options={
                'verbose_name': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='FestivalPageRatebleAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.FestivalPageRateableAttribute')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateable_attributes', to='home.FestivalPage')),
            ],
        ),
        migrations.RemoveField(
            model_name='festivalattributevalue',
            name='foreign',
        ),
        migrations.RemoveField(
            model_name='festivalattributevalue',
            name='page',
        ),
        migrations.DeleteModel(
            name='FestivalAttribute',
        ),
        migrations.DeleteModel(
            name='FestivalAttributeValue',
        ),
    ]
