# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160318_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalPageTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='home.FestivalPage')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Test')),
            ],
        ),
    ]
