# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160318_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalpagerateableattribute',
            name='page',
        ),
    ]
