# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_festivalpagerateableattribute_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalpagetest',
            name='page',
        ),
        migrations.RemoveField(
            model_name='festivalpagetest',
            name='test',
        ),
        migrations.RemoveField(
            model_name='festivalpage',
            name='test_attribute',
        ),
        migrations.DeleteModel(
            name='FestivalPageTest',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
