# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160318_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
