# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0017_festivalpage_descr'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='festivalpage',
            name='data',
            field=models.DateField(null=True, verbose_name='Festival Datum'),
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='descr',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default='', verbose_name='Festival promo tekst'),
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Festival naam'),
        ),
        migrations.AlterField(
            model_name='festivalpageratebleattributevalue',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateable_attributes', to='home.FestivalPage'),
        ),
    ]
