# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20160320_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festivalpage',
            old_name='data',
            new_name='date',
        ),
    ]
