# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20160320_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.AddressInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=28)),
                ('last_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'person',
            },
        ),
        migrations.AlterModelOptions(
            name='festivalpage',
            options={'ordering': ['-date'], 'verbose_name': 'FestivalPagina'},
        ),
        migrations.AlterModelManagers(
            name='festivalpage',
            managers=[
                ('upcoming', django.db.models.manager.Manager()),
            ],
        ),
    ]
