# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20160320_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name'], 'verbose_name': 'person'},
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='date',
            field=models.DateField(null=True, verbose_name='Festival datum'),
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='Duur (# dagen)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festivals', to='home.AddressInformation'),
        ),
    ]
