# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20160320_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpage',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festivals', to='home.Location'),
        ),
    ]
