# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20160322_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalimage',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.FestivalPage'),
        ),
        migrations.AlterField(
            model_name='festivalimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
