# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('home', '0028_auto_20160322_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpage',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='festivalimage',
            name='festival',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.FestivalPage'),
        ),
    ]
