# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 10:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20160322_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalimage',
            name='festival',
        ),
        migrations.RemoveField(
            model_name='festivalpage',
            name='test',
        ),
        migrations.AddField(
            model_name='festivalimage',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.FestivalPage'),
        ),
    ]
