# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20160329_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
