# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_customimage_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='test',
        ),
        migrations.AddField(
            model_name='festivalimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
