# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20160403_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=8, null=True, verbose_name='nummer'),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=8, null=True, verbose_name='postcode'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=40, null=True, verbose_name='straat'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=40, verbose_name='stad/gemeente'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='home.Address', verbose_name='adres'),
        ),
    ]
