# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='home.Address', verbose_name='adres'),
        ),
    ]
