# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20160404_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalpage',
            name='test',
        ),
    ]
