# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20160404_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalpage',
            name='tags',
        ),
        migrations.AlterField(
            model_name='festivalpage',
            name='name',
            field=models.CharField(default='', max_length=40, unique=True, verbose_name='Festival naam'),
        ),
    ]
