# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20160405_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpage',
            name='website',
            field=models.URLField(max_length=120, null=True),
        ),
    ]
