# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_festivalpage_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='festivalimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='hoofdafbeelding'),
        ),
    ]
